name: Terraform CI

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/terraform-ci.yml'
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform Init + Validate + Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: examples/single-account

      - name: Terraform Validate
        run: terraform validate
        working-directory: examples/single-account

      - name: Terraform Plan
        run: terraform plan
        working-directory: examples/single-account
